Repository IT-Pick/IT-Pick-Frontend, pull requests merged in 2024-07, with the labels that each got.

#2 [FEAT/#1] 마이페이지 UI 구현
  src/App.css
  src/App.tsx
  src/assets/images/ic_alarm.svg
  src/assets/images/ic_profile.svg
  src/index.css
  src/main.tsx
  src/pages/MyPage/MyPage.tsx
  tailwind.config.js
Labels: ⭐ [FEAT], 💟 [UI], 🐬 윤서

#8 [FEAT/#3] 회원가입 페이지 구현
  src/App.tsx
  src/assets/images/ic_alarm.svg
  src/assets/images/ic_btn_certify_able.svg
  src/assets/images/ic_btn_certify_unable.svg
  src/assets/images/ic_btn_sign_up_able.svg
  src/assets/images/ic_btn_sign_up_unable.svg
  src/assets/images/ic_checkbox_checked.svg
  src/assets/images/ic_checkbox_unchecked.svg
  src/assets/images/ic_icon_hide.svg
  src/assets/images/ic_icon_show.svg
  src/assets/images/ic_profile.svg
  src/index.css
  src/main.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  tailwind.config.js
Labels: ⭐ [FEAT], 💟 [UI], 🐬 윤서

#10 [FIX/#3] 회원가입 페이지 구현 (PR Revert)
  src/assets/images/ic_btn_certify_able.svg
  src/assets/images/ic_btn_certify_unable.svg
  src/assets/images/ic_btn_sign_up_able.svg
  src/assets/images/ic_btn_sign_up_unable.svg
  src/assets/images/ic_checkbox_checked.svg
  src/assets/images/ic_checkbox_unchecked.svg
  src/assets/images/ic_icon_hide.svg
  src/assets/images/ic_icon_show.svg
  src/main.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  tailwind.config.js
Labels: 🔧 [FIX], 🐬 윤서

#12 [FEAT/#4] 홈 페이지 구현
  src/App.tsx
  src/assets/images/16x16/tag_ico_comment.svg
  src/assets/images/16x16/tag_ico_delete.svg
  src/assets/images/16x16/tag_ico_right.svg
  src/assets/images/16x16/tag_ico_view.svg
  src/assets/images/16x16/tag_ico_visibility.svg
  src/assets/images/16x16/tag_ico_vote.svg
  src/assets/images/24x24/ico_alarm.svg
  src/assets/images/24x24/ico_camera.svg
  src/assets/images/24x24/ico_mypage.svg
  src/assets/images/24x24/ico_roundcheck_filled.svg
  src/assets/images/24x24/ico_roundcheck_outline.svg
  src/assets/images/24x24/ico_search.svg
  src/assets/images/24x24/ico_send.svg
  src/assets/images/24x24/ico_squarecheck_checked.svg
  src/assets/images/24x24/ico_squarecheck_unchecked.svg
  src/assets/images/24x24/ico_visibility_hidden.svg
  src/assets/images/24x24/ico_visibility_visible.svg
  src/assets/images/CommunityLogo/daumcafe.svg
  src/assets/images/CommunityLogo/dcinside.svg
  src/assets/images/CommunityLogo/namuwiki.svg
  src/assets/images/CommunityLogo/naver.svg
  src/assets/images/CommunityLogo/twitter.svg
  src/assets/images/LiveDiscussion/LiveDiscussion1.png
  src/assets/images/LiveDiscussion/LiveDiscussion2.png
  src/assets/images/LiveDiscussion/LiveDiscussion3.png
  src/assets/images/etc/ico_camera_mypage.svg
  src/assets/images/etc/ico_logout.svg
  src/assets/images/etc/ico_trash.svg
  src/assets/images/etc/ico_write.svg
  src/assets/images/etc/logo.png
  src/assets/images/ico_alarm.svg
  src/assets/images/ico_mypage.svg
  src/assets/images/ico_search.svg
  src/assets/images/touch/all_body_btn.svg
  src/index.css
  src/main.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/component/CommunityRanking.tsx
  src/pages/HomePage/component/Header.tsx
  src/pages/HomePage/component/IntegratedRanking.tsx
  src/pages/HomePage/component/LiveDiscussion.tsx
  src/pages/HomePage/component/SearchBar.tsx
  src/pages/RankingPage/RankingPage.tsx
  tailwind.config.js
Labels: ⭐ [FEAT], 💟 [UI], 🎲 clice

#14 [FEAT/#6,7] 로그인, 마이페이지 구현
  package.json
  src/App.tsx
  src/assets/images/non_visibility.svg
  src/assets/images/visibility.svg
  src/main.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/ProfilePage/Keypad.tsx
  src/pages/ProfilePage/ProfilePage.tsx
Labels: ⭐ [FEAT], 💟 [UI], 😺 서진

#16 [FEAT/#15] 마이페이지 - 내가 만든 토론/내가 참여한 토론
  src/assets/images/16x16/tag_ico_view.svg
  src/main.tsx
  src/pages/MyPage/Debate.tsx
  src/pages/MyPage/ParticipatedDebate.tsx
Labels: ⭐ [FEAT], 💟 [UI], 😺 서진

#19 [FEAT/#5] 랭킹 페이지 구현
  package.json
  pnpm-lock.yaml
  src/main.tsx
  src/pages/RankingPage/.gitkeep
  src/pages/RankingPage/RankingPage.tsx
  src/pages/RankingPage/components/CategorySlider.tsx
  src/pages/RankingPage/components/MenuSelector.tsx
  src/pages/RankingPage/components/TrendItem.tsx
  src/pages/RankingPage/components/TrendList.tsx
  src/sotre/.gitkeep
  src/store/trendStore.ts
Labels: ⭐ [FEAT], 💟 [UI], 🎲 clice

#20 [FEAT/#18] 프로필 편집 화면 구현
  src/assets/images/ico_profile_edit.svg
  src/main.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/ProfileEditPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
Labels: ⭐ [FEAT], 💟 [UI], 🐬 윤서

#21 [FEAT/#17] 비밀번호 변경 화면 구현
  src/pages/MyPage/PwdChangePage.tsx
Labels: ⭐ [FEAT], 💟 [UI], 🐬 윤서

#26 [FEAT/#23] 라우터 페이지간 이동 구현
  package.json
  public/_redirects
  src/App.tsx
  src/main.tsx
  src/pages/ChangeInfoPage/ProfileEditPage.tsx
  src/pages/ChangeInfoPage/PwdChangePage.tsx
  src/pages/HistoryPage/Debate.tsx
  src/pages/HistoryPage/ParticipatedDebate.tsx
  src/pages/HomePage/component/Header.tsx
  src/pages/HomePage/component/IntegratedRanking.tsx
  src/pages/LoginPage/.gitkeep
  src/pages/MyPage/.gitkeep
  src/pages/MyPage/MyPage.tsx
  src/pages/SetProfile/Keypad.tsx
  src/pages/SetProfile/NewSetProfile.tsx
  src/pages/SetProfile/SetProfile.tsx
  tsconfig.app.json
Labels: ⭐ [FEAT], 🎲 clice

#34 [FEAT/#32] 로그인 여부에 따라 홈화면 환영인사 다르게 표시하는 기능 구현
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/component/GreetingMessage.tsx
  src/pages/HomePage/component/Header.tsx
  src/pages/HomePage/component/SearchBar.tsx
Labels: ⭐ [FEAT], 💟 [UI], 🎲 clice

#36 [FIX/#30] 회원가입 페이지 구현 수정
  src/main.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/components/Checkbox.tsx
  src/pages/SignUpPage/components/InputField.tsx
  src/pages/SignUpPage/utils/validation.tsx
Labels: 🔧 [FIX], 🐬 윤서

#37 [FEAT/#28] 회원가입 약관 동의 화면 구현
  src/main.tsx
  src/pages/AgreementPage/AgreementPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/component/LiveDiscussion.tsx
  src/pages/LoginPage/LoginPage.tsx
Labels: ⭐ [FEAT], 💟 [UI], 😺 서진

#35 [FEAT/#27] 토론/알림 예외 화면 구현
  src/main.tsx
  src/pages/HistoryPage/Debate.tsx
  src/pages/HistoryPage/ParticipatedDebate.tsx
Labels: ⭐ [FEAT], 💟 [UI], 😺 서진
