Repository IT-Pick/IT-Pick-Frontend, pull requests merged in 2024-08, with the labels that each got.

#46 [FEAT/#33]: 알림 페이지 구현
  src/components/AlarmButton.tsx
  src/data/.gitkeep
  src/data/alarms.ts
  src/main.tsx
  src/pages/HomePage/component/Header.tsx
  src/pages/HomePage/component/SearchBar.tsx
  src/pages/MyAlarmPage/MyAlarmPage.tsx
  src/pages/MyAlarmPage/components/AlarmItem.tsx
  src/pages/MyPage/MyPage.tsx
  src/utils/.gitkeep
  src/utils/timeUtils.ts
Labels: ⭐ [FEAT], 💟 [UI], 🎲 clice

#45 [FEAT/#24] 검색 페이지 화면 구현, 에러 페이지 로고 수정
  src/assets/images/16x16/tag_ico_delete_black.svg
  src/assets/images/ico_error_logo.png
  src/components/SearchBar.tsx
  src/main.tsx
  src/pages/ErrorPage/404ErrorPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/components/405ErrorPage.tsx
  src/pages/SearchPage/components/DiscussionCard.tsx
  src/pages/SearchPage/components/PopularSearches.tsx
  src/pages/SearchPage/components/RecentDiscussions.tsx
  src/pages/SearchPage/components/RecentSearches.tsx
  src/pages/SearchPage/components/SearchBar.tsx
  src/pages/SearchPage/components/SearchResultItem.tsx
Labels: 🛠️ [CHORE], ⭐ [FEAT], 💟 [UI], 🐬 윤서

#49 [REFACTOR/#44] 로그아웃, 탈퇴하기 다이알로그 리팩토링
  src/components/ActionButton.tsx
  src/components/CancelButton.tsx
  src/components/DeleteAccountButton.tsx
  src/components/DeleteAccoutModal.tsx
  src/components/LogoutButton.tsx
  src/components/LogoutModal.tsx
  src/components/Modal/DeleteAccoutModal.tsx
  src/components/Modal/DialogModal.tsx
  src/components/Modal/LogoutModal.tsx
  src/pages/ChangeInfoPage/ProfileEditPage.tsx
  src/pages/MyPage/MyPage.tsx
Labels: 🔧 [FIX], ♻️ [REFACTOR], 💟 [UI], 🎲 clice

#52 [FIX/#50] 마이페이지 & 로그인 페이지 CSS QA 반영
  src/pages/HistoryPage/Debate.tsx
  src/pages/LoginPage/LoginPage.tsx
Labels: 🔧 [FIX], 💟 [UI], 😺 서진

#54 [ REFACTOR/#53]: @path aliases 경로 별칭 추가
  tsconfig.node.json
Labels: ♻️ [REFACTOR], 🎲 clice

#57 [FEAT/#47] 실시간 토론 글 첫 화면 구현, 디자인 QA 반영
  src/assets/images/16x16/tag_ico_pic.svg
  src/assets/images/16x16/tag_ico_pic_gray.svg
  src/assets/images/16x16/tag_ico_vote_gray.svg
  src/components/DiscussionCard.tsx
  src/main.tsx
  src/pages/ChangeInfoPage/ProfileEditPage.tsx
  src/pages/KeywordPage/KeywordPage.tsx
  src/pages/SearchPage/.gitkeep
  src/pages/WritePostPage/DebateCreatePage.tsx
  src/pages/WritePostPage/components/DebateIconBar.tsx
Labels: ⭐ [FEAT], 🔧 [FIX], 💟 [UI], 🐬 윤서

#60 [FEAT/#51] 게시된 실시간 토론글
  src/assets/images/24x24/ico_heart.png
  src/assets/images/24x24/ico_heart_filled.svg
  src/assets/images/24x24/ico_more.svg
  src/assets/images/ico_more-vertical.svg
  src/assets/images/ico_profile2.svg
  src/main.tsx
  src/pages/UploadedVotePage/UploadedPage.tsx
  src/pages/UploadedVotePage/components/AddComment.tsx
  src/pages/UploadedVotePage/components/Comment.tsx
  src/pages/UploadedVotePage/components/CommentList.tsx
  src/pages/UploadedVotePage/components/Content.tsx
  src/pages/UploadedVotePage/components/Header.tsx
Labels: ⭐ [FEAT], 💟 [UI], 😺 서진

#61 [FEAT/#56] 관심주제 페이지
  src/assets/images/40x40/ico_culture.svg
  src/assets/images/40x40/ico_food.svg
  src/assets/images/40x40/ico_letter.svg
  src/assets/images/40x40/ico_lightbulb.svg
  src/assets/images/40x40/ico_money.svg
  src/assets/images/40x40/ico_music.svg
  src/assets/images/40x40/ico_sports.svg
  src/assets/images/40x40/ico_travel.svg
  src/assets/images/40x40/ico_world.svg
  src/main.tsx
  src/pages/AgreementPage/AgreementPage.tsx
  src/pages/ChangeInfoPage/ProfileEditPage.tsx
  src/pages/InterestPage/InterestPage.tsx
  src/pages/InterestPage/component/CompleteBtn.tsx
  src/pages/InterestPage/component/Header.tsx
  src/pages/InterestPage/component/Item.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/SetProfile/NewSetProfile.tsx
  src/pages/SetProfile/SetProfile.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  tailwind.config.js
Labels: ⭐ [FEAT], 💟 [UI], 😺 서진

#62 [FIX/#59] 회원가입 페이지 UI 및 기능 수정
  src/assets/images/24x24/ico_code_roundcheck_unable.svg
  src/assets/images/ic_btn_certify_able.svg
  src/assets/images/ic_btn_certify_unable.svg
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/components/InputField.tsx
  src/pages/SignUpPage/utils/validation.tsx
Labels: 🔧 [FIX], 💟 [UI], 🐬 윤서

#63 [FIX/#58] 랭킹 페이지 디자인 QA 반영
  src/assets/images/24x24/ico_left_arrow_gray2.svg
  src/assets/images/24x24/ico_right_arrow_gray2.svg
  src/assets/images/ico_dot_point.svg
  src/pages/RankingPage/RankingPage.tsx
  src/pages/RankingPage/components/CategorySlider.tsx
  src/pages/RankingPage/components/DateDisplay.tsx
  src/pages/RankingPage/components/MenuSelector.tsx
  src/pages/RankingPage/components/TrendItem.tsx
Labels: 🔧 [FIX], 💟 [UI], 🐬 윤서

#72 [FEAT/#65] 회원가입 서버 통신 프로세스 완료
  src/apis/emailDuplicateCheck.ts
  src/apis/getEmailVerification.ts
  src/apis/nicknameDuplicateCheck.ts
  src/apis/sendEmailVerification.ts
  src/apis/signUp.ts
  src/assets/images/24x24/ico_code_roundcheck_able.svg
  src/pages/AgreementPage/AgreementPage.tsx
  src/pages/InterestPage/InterestPage.tsx
  src/pages/InterestPage/component/CompleteBtn.tsx
  src/pages/InterestPage/component/Item.tsx
  src/pages/SetProfile/Keypad.tsx
  src/pages/SetProfile/NewSetProfile.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/components/InputField.tsx
Labels: ⭐ [FEAT], 🔧 [FIX], 🐬 윤서, 🖥️ 서버통신

#71 [FEAT/69] 로그인 API 연결, 액세스 토큰 추가
  src/App.css
  src/apis/loginUser.ts
  src/apis/refreshAccessToken.ts
  src/assets/images/.gitkeep
  src/assets/images/victory_banner.png
  src/components/AlarmButton.tsx
  src/components/DiscussionCard.tsx
  src/components/PrivateRoute.tsx
  src/context/AuthContext.tsx
  src/index.css
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/component/CommunityRanking.tsx
  src/pages/HomePage/component/GreetingMessage.tsx
  src/pages/HomePage/component/Header.tsx
  src/pages/HomePage/component/IntegratedRanking.tsx
  src/pages/HomePage/component/LiveDiscussion.tsx
  src/pages/HomePage/component/SearchBar.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/SearchPage/components/DiscussionCard.tsx
  src/pages/SearchPage/components/RecentDiscussions.tsx
  tailwind.config.js
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
Labels: ⭐ [FEAT], 🎲 clice, 🖥️ 서버통신

#74 [FEAT/#70] 프로필 사진 설정(변경) 구현, 멀티파트 서버통신
  src/apis/editProfileImage.ts
  src/apis/getMyPageUserInfo.ts
  src/apis/getUserNickname.ts
  src/assets/images/ico_camera.svg
  src/assets/images/ico_profile_default.svg
  src/index.css
  src/pages/ChangeInfoPage/ProfileEditPage.tsx
  src/pages/HomePage/component/GreetingMessage.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  vite.config.ts
Labels: ⭐ [FEAT], 🐬 윤서, 🖥️ 서버통신

#75 [FEAT/#43] 투표 컴포넌트 중간 구현
  src/assets/images/16x16/tag_ico_vote_gray.svg
  src/assets/images/etc/ico_vote_add_photo.svg
  src/assets/images/etc/ico_vote_delete_item_active.svg
  src/assets/images/etc/ico_vote_delete_item_unactive.svg
  src/assets/images/ico_empty_photo.svg
  src/main.tsx
  src/pages/KeywordPage/KeywordPage.tsx
  src/pages/MakeVote/MakeVote.tsx
  src/pages/MakeVote/component/ItemInput.tsx
  src/pages/MakeVote/component/MakeVoteBar.tsx
  src/pages/WritePostPage/.gitkeep
  src/pages/WritePostPage/DebateCreatePage.tsx
  src/pages/WritePostPage/components/DebateIconBar.tsx
  src/pages/WritePostPage/components/VoteResult.tsx
  tsconfig.node.json
  vite.config.ts
Labels: ⭐ [FEAT], 💟 [UI], 🎲 clice

#81 [FEAT/#79] 회원가입 완료 후 로그인 이동 화면 (환영 인사)
  src/assets/images/itpickWhiteLogo.png
  src/main.tsx
  src/pages/InterestPage/component/CompleteBtn.tsx
  src/pages/InterestPage/component/Header.tsx
  src/pages/SignUpandGreetingPage/SignUpandGreeetingPage.tsx
Labels: ⭐ [FEAT], 💟 [UI], 🎲 clice

#88 [REFACTOR/#73] 홈화면 최종 QA
  src/assets/images/CommunityLogo/google.svg
  src/assets/images/CommunityLogo/nate.svg
  src/assets/images/CommunityLogo/zum.svg
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/component/CommunityRanking.tsx
  src/pages/HomePage/component/Header.tsx
Labels: ♻️ [REFACTOR], 💟 [UI], 😺 서진

#89 [FEAT/#66] 랭킹 조회 API 연결, 서버 통신 코드 로직 수정
  .gitignore
  src/apis/getRankingInfo.ts
  src/apis/patchLikedTopics.ts
  src/apis/patchNickname.ts
  src/apis/patchPwd.ts
  src/pages/ChangeInfoPage/InterestEdit/component/CompleteBtn.tsx
  src/pages/ChangeInfoPage/ProfileEditPage.tsx
  src/pages/ChangeInfoPage/PwdChangePage.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/RankingPage/RankingPage.tsx
  src/pages/RankingPage/components/CategorySlider.tsx
  src/pages/RankingPage/components/MenuSelector.tsx
  src/pages/RankingPage/components/TrendList.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/store/trendStore.ts
  vite.config.ts
Labels: ⭐ [FEAT], 🔧 [FIX], 🐬 윤서, 🖥️ 서버통신

#90 [FEAT/#87] 내가 만든 토론, 내가 참여한 토론 API 연결
  src/apis/getInvolvedDebate.ts
  src/apis/getMyDebate.ts
  src/main.tsx
  src/pages/HistoryPage/Debate.tsx
  src/pages/HistoryPage/ParticipatedDebate.tsx
  src/pages/MyPage/MyPage.tsx
Labels: ⭐ [FEAT], 💟 [UI], 😺 서진, 🖥️ 서버통신

#95 [FEAT/#86] 검색 페이지 구현 중간 PR
  src/apis/getKeyword.ts
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/components/PopularSearches.tsx
  src/pages/SearchPage/components/SearchResultItem.tsx
  vite.config.ts
Labels: ⭐ [FEAT], 🐬 윤서, 🖥️ 서버통신

#96 [FEAT/#55] 모든 브라우저에서 랭킹 카테고리, 전체 페이지 스크롤 바 숨김 구현
  src/index.css
  src/pages/RankingPage/components/CategorySlider.tsx
Labels: ⭐ [FEAT], 💟 [UI], 🎲 clice

#98 [DESIGN/#97]:검색바 깜빡이는 커서 색 보라색으로 변경
  src/components/SearchBar.tsx
  src/index.css
  src/pages/HomePage/HomePage.tsx
Labels: ♻️ [REFACTOR], 💟 [UI], 🎲 clice

#101 [FEAT/#86] 검색 페이지 API 연결 및 로컬 스토리지 구현, 홈화면 실시간 시간 수정
  src/assets/images/LiveDiscussion/PurpleBox.tsx
  src/assets/images/ico_purple_box.svg
  src/components/SearchBar.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/component/CommunityRanking.tsx
  src/pages/HomePage/component/IntegratedRanking.tsx
  src/pages/HomePage/component/LiveDiscussion.tsx
  src/pages/HomePage/component/SearchBar.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/components/PopularSearches.tsx
  src/pages/SearchPage/components/RecentSearches.tsx
  src/store/trendStore.ts
Labels: ⭐ [FEAT], 🔧 [FIX], 💟 [UI], 🐬 윤서, 🖥️ 서버통신

#108 [FEAT/#100] 홈 화면 GET API 연결 (통합 랭킹, 커뮤니티 별 랭킹) 연결
  src/apis/getCommunityRankingKeyword.ts
  src/apis/getLiveDiscussionBest3.ts
  src/components/DiscussionCard.tsx
  src/pages/HomePage/component/CommunityRanking.tsx
  src/pages/HomePage/component/IntegratedRanking.tsx
  src/pages/HomePage/component/LiveDiscussion.tsx
  src/pages/SearchPage/SearchPage.tsx
Labels: ⭐ [FEAT], 💟 [UI], 🐬 윤서, 🖥️ 서버통신

#110 [HOTFIX/#100] Request Url Error
  src/apis/getCommunityRankingKeyword.ts
  src/apis/getLiveDiscussionBest3.ts
Labels: 😲 [HOTFIX], 🖥️ 서버통신

#111 [HOTFIX/#100] Request Url Error Again ..
  src/apis/getCommunityRankingKeyword.ts
Labels: 😲 [HOTFIX], 🖥️ 서버통신

#119 [FEAT/#100] 검색 페이지 최근 본 토론 GET API 연결
  src/apis/getRecentDiscussion.ts
  src/components/DiscussionCard.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/components/RecentDiscussions.tsx
Labels: ⭐ [FEAT], 💟 [UI], 🐬 윤서, 🖥️ 서버통신

#124 [FIX/#43] 투표 옵션 타입 수정 및 부모 컴포넌트에서 텍스트와 이미지를 처리할 수 있도록 createDebate API, ItemInput 컴포넌트 수정
  src/apis/WriteDebate/createDebate.ts
  src/pages/MakeVote/component/ItemInput.tsx
Labels: 🔧 [FIX], 🎲 clice, 🖥️ 서버통신

#125 [FEAT/43] 투표 컴포넌트 사진 업로드 기능 구현중
  src/context/.gitkeep
  src/pages/MakeVote/MakeVote.tsx
  src/pages/MakeVote/component/ItemInput.tsx
Labels: ⭐ [FEAT], 🎲 clice, 🖥️ 서버통신

#133 [FEAT/#122] 키워드 관련 자료 GET API 연결
  src/apis/getKeywordRelatedData.ts
  src/context/KeywordStateContext.tsx
  src/main.tsx
  src/pages/KeywordPage/KeywordPage.tsx
  src/pages/KeywordPage/component/Header.tsx
  src/pages/KeywordPage/component/MainCard.tsx
  src/pages/KeywordPage/component/Popular.tsx
  src/pages/KeywordPage/component/RelatedData.tsx
  src/pages/RankingPage/components/TrendList.tsx
Labels: ⭐ [FEAT], 🐬 윤서, 🖥️ 서버통신

#134 [HOTFIX] 관련 자료 rank url error
  public/_redirects
Labels: 😲 [HOTFIX], 🖥️ 서버통신

#140 [FEAT/#122] 키워드 관련 토론 조회 API 연결, empty view 처리
  src/apis/getKeywordLiveDiscussion.ts
  src/pages/KeywordPage/KeywordPage.tsx
  src/pages/KeywordPage/component/LiveDiscussion.tsx
  src/pages/KeywordPage/component/Popular.tsx
  src/pages/KeywordPage/component/RecentDiscussion.tsx
Labels: ⭐ [FEAT], 🐬 윤서, 🖥️ 서버통신

#143 [FEAT/#83] 토론 글 이미지 업로드
  src/pages/UploadedVotePage/components/Content.tsx
Labels: ⭐ [FEAT], 💟 [UI], 🎲 clice, 🖥️ 서버통신

#147 [FIX/#142] 마무리 작업
  src/components/DiscussionCard.tsx
  src/pages/ChangeInfoPage/ProfileEditPage.tsx
  src/pages/KeywordPage/KeywordPage.tsx
  src/pages/MyAlarmPage/MyAlarmPage.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/components/PopularSearches.tsx
  src/pages/SearchPage/components/SearchResultItem.tsx
Labels: 🔧 [FIX], 🐬 윤서

#150 [FIX/#149] CSS 수정
  src/components/DiscussionCard.tsx
  src/pages/HistoryPage/Debate.tsx
  src/pages/HistoryPage/ParticipatedDebate.tsx
  src/pages/HomePage/component/LiveDiscussion.tsx
  src/pages/MyAlarmPage/MyAlarmPage.tsx
  src/pages/SearchPage/components/RecentDiscussions.tsx
Labels: 🔧 [FIX], 💟 [UI], 😺 서진

#151 [FIX] 키워드 상세 header
  src/pages/KeywordPage/component/Header.tsx
Labels: 💟 [UI], 🐬 윤서
